version: '3'

services:
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  goupfile:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
